server:
  servlet:
    context-path: /m1
  port: 8089
spring:
  datasource:
#     url: jdbc:mysql://39.105.129.92:3306/Medicaldevice?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      url: jdbc:mysql://39.105.129.92:3306/Medicaldevice?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding-utf8&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Root!!2018
mybatis:
  #  全局配置文件
  #  config-location: classpath:mybatis/mybatis-config.xml
  #  sql映射文件
  mapper-locations: classpath:/mapper/**/*.xml
  #  写了这个配置就不用写全局配置文件了
  configuration:
    map-underscore-to-camel-case: true